version: "3.9"

services:
  backend:
    image: yowon123/ai_agent_diet_scheduler_backend:latest
    env_file:
      - .env
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlite:///db/agent.db  # /app/agent.db 기준 - /app 안에 agent.db 파일이 생성된다는 것

  frontend:
    image: yowon123/ai_agent_diet_scheduler_frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
